### ISSUE TITLE
01-ataribaby

### ISSUE THREAD

**Issue by lamasutra** [lamasutra/cwr3-resistance-issues#1]
Viktor nesedi v aute na konci intra 00:07:03
Auto stoji uprostred silnice 00:14:20
Auto stoji uprostred silnice 00:16:16
Blaznive BMP v cutscene prejede vlastni a narazi do dalsiho BMP 00:28:00
Tlacikto OK, vypada to divne a nekdo si mozna nevsimne 00:31:24
Tlacikto OK, vypada to divne a nekdo si mozna nevsimne 00:47:50

https://www.youtube.com/watch?v=2pc7yR15vMc

**Comment by ataribaby42** [comment]
Alpha 5 
Viktor nesedi v aute na konci intra - opraveno
Blaznive BMP v cutscene prejede vlastni a narazi do dalsiho - opraveno zkracenim cutsceny?
Tlacikta OK - opraveno, tlacikta tam uz nejsou

**Comment by lamasutra** [comment]
To BVP jsem zatim neresil, podivam se na to, az doladim cesky dabing
