### ISSUE TITLE
Test zacatku Alpha 5

### ISSUE THREAD

**Issue by ataribaby42** [lamasutra/cwr3-resistance-issues#2]
https://www.youtube.com/watch?v=WTUMLcHP1aA

- Zmateny skodovkar v cervene skodovce - lepsi ho odstranit? 00:12:39
- Zmateny autobusak 00:15:13
- Troska nesedi na zidli ale pred ni - vypada to divne a buguje do stolu - regrese od Alpha 4 (https://youtu.be/2pc7yR15vMc?t=2112) 00:29:00 
- Auta blokujici silnici opravena ale mozna nahodne ( zlute auto zmatene na prave strane silnice)
![image](https://user-images.githubusercontent.com/54838824/189533893-9c472835-6640-455d-bf50-a2d6f32c9af8.png)

**Comment by lamasutra** [comment]
- V alfe ver 6 bude nastaveni speedLimit pro nektere vozidla na 50 - melo by to zabranit stretu vozidla s autobusem a tim jeho zastaveni. Doted jezdil bus pomalu a ostatni vozy mnohem rychleji, AI to obcas nedava.
- Upravil jsem cutscenu, osoby u stolu jsou usazeny jinym zpusobem a pri zmene akce uz by nemelo dochazet k posunu

**Comment by lamasutra** [comment]
zaviram, vsechno by melo byt opraveno v alfe 8
