### ISSUE TITLE
Test Alpha 7

### ISSUE THREAD

**Issue by ataribaby42** [lamasutra/cwr3-resistance-issues#3]
Kampan restartovana pod Alfa 7. Dohrano az po misi Scarp. 

Nejvetsi problem je porad autobus. Poprve se zasekl pred zastavkou, po dobehnuti a nastoupeni cutscena pokracovala a pak se autobus bugnul. Pokud to nepujde opravit, tak se to musi napsat do readme nebo neceho jako known issues, aby to lidi vedeli a kdyztak restartovali misi

https://www.twitch.tv/videos/1600082316?t=2h43m18s

Po restartovani mise vse ok az na to ze ridis prejel zastavku a nedpobrzdil :)

Ammo Low dost tezke, specialne kdyz mi padla mlha a dest. Ale to muze byt tim ze sem levej, Nakonec sem to nak udelal.

Jeden divak na streamu si vsimnul ze cedule zastavky je pred zastavkou a ne za zastavkou :) Zastavka v poacnem smeru to ma ok. Asi chyba mapy a ne kampane. Detail, ja sem si toho ani nevsiml.

Ty zamerovace tanku jsou strasne, nevedel sem kam strilet, az pak zjistil ze ne klasicky na strisku ketra se ma hybat se zvolenym namerem ale na to kolecko uprostred, pak V3S co jede 100 je taky peklo a jak si rikal ty nakladaky strasne valej, specialne z kopce, Skoda taky. A tanky jak jsou rychle a pohyblive, takove drifty, to neni pekne. To ale chapu, ze neni problem kampane, ale CRW3 jako takoveho.

Persistence vybaveni postavicek a weapon poolu fungovala dobre. Co sem nalootil to sem mel.

Zaznam streamu, bude tam jen par dni:
https://www.twitch.tv/videos/1600082316?t=2h43m13s

Jednou to vyhodilo scripting error ale zatim se to misto na stramu nenasel, asi to bude kvuli rank systemu, jel sem s puvodnim profilem. Pamatuji si ze to bylo neco ohledne ranku. Radeji pripojuji cely log ze hrani. Pokusim se to misto na streamu najit.

[Arma3_x64_2022-09-24_21-16-49.zip](https://github.com/lamasutra/cwr3-resistance-issues/files/9639814/Arma3_x64_2022-09-24_21-16-49.zip)

**Comment by ataribaby42** [comment]
Autobus se zda ted vzdy nedobrzdi

![image](https://user-images.githubusercontent.com/54838824/192124388-b6465516-5643-4054-96af-41306a4a3d95.png)

**Comment by ataribaby42** [comment]
Tady je ta script chyba, stane se kdyz me poprve zabijou v Ammo Low

![image](https://user-images.githubusercontent.com/54838824/192125216-68abb9f7-c2e8-48fe-af20-e2456a028dff.png)

**Comment by ataribaby42** [comment]
Uz vim proc mi poprve neslo skoncit SCRAP
v teto stodole se AI zasekne a neumi jit ven

![image](https://user-images.githubusercontent.com/54838824/192126856-3ec00819-06b1-4f31-9389-97b4ce7befb1.png)

**Comment by lamasutra** [comment]
closing
