### ISSUE TITLE
Test Alpha 7, mise Occupation

### ISSUE THREAD

**Issue by ataribaby42** [lamasutra/cwr3-resistance-issues#4]
Mise Occupation (10 mise tusim) asi vubec nefunguje, posili nedojeli a co je horsi nepratelky armor stal na miste a na zakadnu se nikdy nevydal, i kdyz sem ho na mape nasel a znicil mise neskoncila
koukal sem jak to fungovalo v puvodnim datadisku a tam vse ok, prijelo a mise skoncila ok
spousta objektu na mape je zabugovanych, AI se z nich u nikdy nedostanou. Dnes se takto namotali do stanu na te zakladne
pak se mi zda ze bedny jsou nak strasne prestrelne v teto misi je v ni 400 zasobnik atd

https://www.twitch.tv/videos/1606238790?t=3h12m55s

**Comment by lamasutra** [comment]
closing

**Comment by lamasutra** [comment]
closing
